name: ChaosMusicPlayer
version: ${version}
main: indi.goldenwater.chaosmusicplayer.ChaosMusicPlayer
authors: [ Golden_Water ]
description: For play music in Minecraft multiplayer mode without mod or resource packs per music.
api-version: 1.18